development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
<<<<<<< HEAD
  url: redis://localhost:6379/1
=======
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
>>>>>>> f11d6087cf3b2fd865875218db25dacd6e60115a
  channel_prefix: rails-mister-cocktail_production
